/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daniel O'Neil (https://sketchfab.com/doneil)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-inktober-2019-pattern-f5fe1e51684d43f786077af696cb2c94
Title: 3D Inktober 2019: Pattern
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function IllustrationLogo(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/illustration-logo.gltf");
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group
                        name="ed7b447cbac5430f98376e87d3b7972cfbx"
                        rotation={[Math.PI / 2, 0, 0]}
                    >
                        <group name="Object_2">
                            <group name="RootNode">
                                <group
                                    name="01_confetti@2x"
                                    position={[-0.435, -0.246, 0]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}
                                >
                                    <mesh
                                        name="01_confetti@2x_01_confetti@2x_0"
                                        geometry={nodes["01_confetti@2x_01_confetti@2x_0"].geometry}
                                        material={materials["01_confetti2x"]}
                                    />
                                </group>
                                <group
                                    name="03_stripes01@2x"
                                    position={[-3.275, -0.051, -1]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}
                                >
                                    <mesh
                                        name="03_stripes01@2x_03_stripes01@2x_0"
                                        geometry={
                                            nodes["03_stripes01@2x_03_stripes01@2x_0"].geometry
                                        }
                                        material={materials["03_stripes012x"]}
                                    />
                                </group>
                                <group
                                    name="03_stripes02@2x"
                                    position={[-3.708, 0.023, -1]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}
                                >
                                    <mesh
                                        name="03_stripes02@2x_03_stripes02@2x_0"
                                        geometry={
                                            nodes["03_stripes02@2x_03_stripes02@2x_0"].geometry
                                        }
                                        material={materials["03_stripes022x"]}
                                    />
                                </group>
                                <group
                                    name="04_paisley@2x"
                                    position={[0.851, -0.449, -1]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={80.497}
                                >
                                    <mesh
                                        name="04_paisley@2x_04_paisley01@2x_0"
                                        geometry={nodes["04_paisley@2x_04_paisley01@2x_0"].geometry}
                                        material={materials["04_paisley012x"]}
                                    />
                                </group>
                                <group
                                    name="05_flower_circle@2x"
                                    position={[0.88, -0.442, -1]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}
                                >
                                    <mesh
                                        name="05_flower_circle@2x_05_flower_circle01@2x_0"
                                        geometry={
                                            nodes["05_flower_circle@2x_05_flower_circle01@2x_0"]
                                                .geometry
                                        }
                                        material={materials["05_flower_circle012x"]}
                                    />
                                </group>
                                <group
                                    name="06_heart_circle@2x"
                                    position={[0, 0, -2]}
                                    rotation={[-Math.PI / 2, 0, 0]}
                                    scale={100}
                                >
                                    <mesh
                                        name="06_heart_circle@2x_06_heart_circle@2x_0"
                                        geometry={
                                            nodes["06_heart_circle@2x_06_heart_circle@2x_0"].geometry
                                        }
                                        material={materials["06_heart_circle2x"]}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    );
}

// useGLTF.preload("/3d.gltf");
