/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ReactLogo(props) {
  const { nodes, materials } = useGLTF("/react-logo.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes["React-Logo_Material002_0"].geometry}
          material={materials["Material.002"]}
          position={[0, 7.9355, 18.1016]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[39.1659, 39.1659, 52.7336]}
        />
      </group>
    </group>
  );
}

// useGLTF.preload("/3d.gltf");
